// Generated by CoffeeScript 1.9.3
(function() {
  window.CONST = window.CONST || {};

  CONST.HOST = 'http://b.bb:8088';

  CONST.HOST_ = 'b.bb:8088';

  CONST.ENUM = CONST.ENUM || {};

  CONST.ENUM.OPS_CATAGORY = {
    'MSG': 0,
    'OPS': 1
  };

  CONST.QINIU_HOST = 'http://7xk1xj.com1.z0.glb.clouddn.com';

}).call(this);
