// Generated by CoffeeScript 1.9.3
(function() {
  $.ws.onopen = function() {
    return $.ws.onmessage = function(evt) {
      var data, msg, ops;
      data = $.parseJSON(evt.data);
      ops = parseInt(data.ops);
      msg = data.msg;
      if (ops === CONST.ENUM.OPS_CATAGORY.MSG) {
        return $('#msg').html(msg);
      } else if (ops === CONST.ENUM.OPS_CATAGORY.OPS) {
        if (msg === 'reload') {
          return location.reload();
        } else if (msg === 'refresh') {
          return console.log('refresh data');
        }
      }
    };
  };

}).call(this);
