// Generated by CoffeeScript 1.9.3
(function() {
  def_view('OpsApp', 'OpsCtrl', function($scope) {
    var o;
    o = {};
    o.msg = '';
    o.ops = CONST.ENUM.OPS_CATAGORY.MSG.toString();
    $scope.o = o;
    return $scope.submit = function() {
      return $.ws.send(o.msg);
    };
  });

}).call(this);
